### PR TITLE
kwargs applied dynamically instead of statically

### PR DESCRIPTION
**Pull request by Deathnerd**
The chain of ifs in the constructor wasn't very pythonic. This is not only pythonic, but easily scalable compared to the last approach.

### CODE REVIEW

**Comment by SodaCookie** [comment]
I agree with removing that chain of if statements as it isn't very Pythonic. I think there should be a check to make sure that setattr isn't adding additional variables to the object as the if statement will not add additional variables unless the key is defined in the chain. For example, if kwarg has a pair of of "foo" : 1, the old code will not create a member self.foo = 1 but the new patch will.

**Comment by Deathnerd** [comment]
How about something like `if key in ('some', 'list', 'of', 'keys'): #set the attribute here` ? That way you have two points of modification (above the `for` loop and inside it) for adding new properties to the class and it's still pythonic

**Comment by SodaCookie** [comment]
Yes I think I'm fine with that. Thanks I'll merge it in.

**Comment by Deathnerd** [comment]
No problem! Any other help needed? I think this is an interesting project

**Comment by SodaCookie** [comment]
@Deathnerd Sorry for the long hiatus, I've had other things on my plate for quite a while and finally have a bit of time during the winter break to pick this project back up. Would you still be interested in contributing to this project?

**Pull request merged**
